name: Linck
description: Your links on your domain
full_description: 'Everything in One Click on your Linck domain. Put all your online things in one place. It is easy to start and use, so everyone can see what you share.
<br>
<br>
## Free Plan<br>
- Your links on linck.io/yourname
- Base analytics
- Basic customization
<br>
<br>
## Pro Plan<br>
- Monthly subscription: $5
- Annual subscription: price per month $1
- Free custom domain
- Domains: .link, .click, .pro, .store
- Unlimited links
- Pre-designed themes
- Views & clicks statistics
- Remove Linck branding
- Advanced customization
<br>
<br>
## Premium Plan<br>
- Monthly subscription: $12
- Annual subscription: price per month $4
- Free custom domain
- Domains: .com, .net, .org, .co, .me
- Unlimited links
- Pre-designed themes
- Views & clicks statistics
- Remove Linck branding
- Advanced customization'
android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - app-store-slide-1.png
  - app-store-slide-2.png
  - app-store-slide-3.png
  - app-store-slide-4.png
  - app-store-slide-5.png
  - app-store-slide-6.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
